version: "3.8"
services:
  user-service:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: user_serviceDB
    ports:
      - "5432:5432"